
version: '3.8'

services:

  db:
    container_name: database
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    env_file:
      ".env"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      ".env"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      ".env"
